# Generated by Django 6.1.2 on 2026-10-07 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('LEVE', 'Leve (até 4 passageiros)'), ('COLETIVO', 'Coletivo (até 18 passageiros)')], max_length=10)),
                ('capacidade', models.PositiveSmallIntegerField(editable=False)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=120)),
                ('setor', models.CharField(max_length=80)),
                ('atividade', models.CharField(max_length=120)),
                ('origem', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('hora_saida', models.TimeField()),
                ('hora_retorno', models.TimeField()),
                ('passageiros', models.PositiveSmallIntegerField()),
                ('categoria_pretendida', models.CharField(blank=True, choices=[('LEVE', 'Leve (até 4 passageiros)'), ('COLETIVO', 'Coletivo (até 18 passageiros)')], max_length=10)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('CANCELADA', 'Cancelada')], default='ATIVA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='reservas.veiculo')),
            ],
            options={
                'ordering': ['data', 'hora_saida'],
            },
        ),
    ]
