# Generated by Django 6.1.2 on 2026-10-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
